"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artemis_vicon.protos.simulation.v1 import vehicle_simulation_pb2 as _vehicle_simulation_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VehicleSimulationServiceStub:
    """自动行驶小车仿真的双向流式服务。"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VehicleSimulationServiceAsyncStub: ...
    StreamEpisode: _grpc.StreamStreamMultiCallable[_vehicle_simulation_pb2.ClientMessage, _vehicle_simulation_pb2.ServerMessage]
    """运行一次仿真 episode。

    客户端首条消息必须是 StartEpisodeRequest；episode 运行期间，客户端持续发送
    VehicleControlCommand 推进仿真，也可以发送 StopEpisodeRequest 主动结束。
    服务端会先返回 EpisodeStarted，再返回若干 ObservationFrame，最终返回
    EpisodeFinished 或 SimulationError。
    """

@_typing.type_check_only
class VehicleSimulationServiceAsyncStub(VehicleSimulationServiceStub):
    """自动行驶小车仿真的双向流式服务。"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamEpisode: _aio.StreamStreamMultiCallable[_vehicle_simulation_pb2.ClientMessage, _vehicle_simulation_pb2.ServerMessage]  # type: ignore[assignment]
    """运行一次仿真 episode。

    客户端首条消息必须是 StartEpisodeRequest；episode 运行期间，客户端持续发送
    VehicleControlCommand 推进仿真，也可以发送 StopEpisodeRequest 主动结束。
    服务端会先返回 EpisodeStarted，再返回若干 ObservationFrame，最终返回
    EpisodeFinished 或 SimulationError。
    """

class VehicleSimulationServiceServicer(metaclass=_abc_1.ABCMeta):
    """自动行驶小车仿真的双向流式服务。"""

    @_abc_1.abstractmethod
    def StreamEpisode(
        self,
        request_iterator: _MaybeAsyncIterator[_vehicle_simulation_pb2.ClientMessage],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_vehicle_simulation_pb2.ServerMessage], _abc.AsyncIterator[_vehicle_simulation_pb2.ServerMessage]]:
        """运行一次仿真 episode。

        客户端首条消息必须是 StartEpisodeRequest；episode 运行期间，客户端持续发送
        VehicleControlCommand 推进仿真，也可以发送 StopEpisodeRequest 主动结束。
        服务端会先返回 EpisodeStarted，再返回若干 ObservationFrame，最终返回
        EpisodeFinished 或 SimulationError。
        """

def add_VehicleSimulationServiceServicer_to_server(servicer: VehicleSimulationServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
