# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from artemis_vicon.protos.simulation.v1 import vehicle_simulation_pb2 as artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artemis_vicon/protos/simulation/v1/vehicle_simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleSimulationServiceStub(object):
    """自动行驶小车仿真的双向流式服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEpisode = channel.stream_stream(
                '/artemis_mudri.simulation.v1.VehicleSimulationService/StreamEpisode',
                request_serializer=artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ClientMessage.SerializeToString,
                response_deserializer=artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ServerMessage.FromString,
                _registered_method=True)


class VehicleSimulationServiceServicer(object):
    """自动行驶小车仿真的双向流式服务。
    """

    def StreamEpisode(self, request_iterator, context):
        """运行一次仿真 episode。

        客户端首条消息必须是 StartEpisodeRequest；episode 运行期间，客户端持续发送
        VehicleControlCommand 推进仿真，也可以发送 StopEpisodeRequest 主动结束。
        服务端会先返回 EpisodeStarted，再返回若干 ObservationFrame，最终返回
        EpisodeFinished 或 SimulationError。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEpisode': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEpisode,
                    request_deserializer=artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ClientMessage.FromString,
                    response_serializer=artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artemis_mudri.simulation.v1.VehicleSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artemis_mudri.simulation.v1.VehicleSimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleSimulationService(object):
    """自动行驶小车仿真的双向流式服务。
    """

    @staticmethod
    def StreamEpisode(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/artemis_mudri.simulation.v1.VehicleSimulationService/StreamEpisode',
            artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ClientMessage.SerializeToString,
            artemis__vicon_dot_protos_dot_simulation_dot_v1_dot_vehicle__simulation__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
