"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _MotorMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MotorModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MotorMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    MOTOR_MODE_STOP: _MotorMode.ValueType  # 0
    MOTOR_MODE_SPEED: _MotorMode.ValueType  # 1
    MOTOR_MODE_DIR: _MotorMode.ValueType  # 2
    MOTOR_MODE_TRACK: _MotorMode.ValueType  # 3
    MOTOR_MODE_DEG: _MotorMode.ValueType  # 4

class MotorMode(_MotorMode, metaclass=_MotorModeEnumTypeWrapper):
    """电机控制模式，对齐 artemis-m0 中 pid_mode_t 的语义。"""

MOTOR_MODE_STOP: MotorMode.ValueType  # 0
MOTOR_MODE_SPEED: MotorMode.ValueType  # 1
MOTOR_MODE_DIR: MotorMode.ValueType  # 2
MOTOR_MODE_TRACK: MotorMode.ValueType  # 3
MOTOR_MODE_DEG: MotorMode.ValueType  # 4
Global___MotorMode: _TypeAlias = MotorMode  # noqa: Y015

@_typing.final
class ClientMessage(_message.Message):
    """客户端发往仿真服务的流式消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    CONTROL_COMMAND_FIELD_NUMBER: _builtins.int
    STOP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start(self) -> Global___StartEpisodeRequest:
        """启动 episode 的请求，必须作为流中的第一条消息发送。"""

    @_builtins.property
    def control_command(self) -> Global___VehicleControlCommand:
        """固件控制层输出的速度目标命令，用于推进一段控制周期。"""

    @_builtins.property
    def stop(self) -> Global___StopEpisodeRequest:
        """主动停止当前 episode 的请求。"""

    def __init__(
        self,
        *,
        start: Global___StartEpisodeRequest | None = ...,
        control_command: Global___VehicleControlCommand | None = ...,
        stop: Global___StopEpisodeRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["control_command", b"control_command", "payload", b"payload", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_command", b"control_command", "payload", b"payload", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["start", "control_command", "stop"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ClientMessage: _TypeAlias = ClientMessage  # noqa: Y015

@_typing.final
class StartEpisodeRequest(_message.Message):
    """启动一次仿真 episode 的参数。"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    RENDER_FIELD_NUMBER: _builtins.int
    MAX_TIME_S_FIELD_NUMBER: _builtins.int
    CONTROL_PERIOD_S_FIELD_NUMBER: _builtins.int
    RANDOM_SEED_FIELD_NUMBER: _builtins.int
    INITIAL_YAW_NOISE_DEG_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """任务编号；为空时由服务端使用默认任务。"""
    render: _builtins.bool
    """是否打开 MuJoCo 可视化窗口。"""
    max_time_s: _builtins.float
    """本次 episode 的最大仿真时长，单位秒；0 表示使用任务默认时间上限。"""
    control_period_s: _builtins.float
    """控制周期，单位秒；0 表示使用仿真后端默认步长。"""
    random_seed: _builtins.int
    """初始航向扰动随机种子；不设置时服务端使用确定性默认。"""
    initial_yaw_noise_deg: _builtins.float
    """初始航向均匀扰动范围，单位度；0 表示不扰动。"""
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        render: _builtins.bool = ...,
        max_time_s: _builtins.float = ...,
        control_period_s: _builtins.float = ...,
        random_seed: _builtins.int | None = ...,
        initial_yaw_noise_deg: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_random_seed", b"_random_seed", "random_seed", b"random_seed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_random_seed", b"_random_seed", "control_period_s", b"control_period_s", "initial_yaw_noise_deg", b"initial_yaw_noise_deg", "max_time_s", b"max_time_s", "random_seed", b"random_seed", "render", b"render", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__random_seed: _TypeAlias = _typing.Literal["random_seed"]  # noqa: Y015
    _WhichOneofArgType__random_seed: _TypeAlias = _typing.Literal["_random_seed", b"_random_seed"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__random_seed) -> _WhichOneofReturnType__random_seed | None: ...

Global___StartEpisodeRequest: _TypeAlias = StartEpisodeRequest  # noqa: Y015

@_typing.final
class VehicleControlCommand(_message.Message):
    """固件控制层输出的车辆控制命令。"""

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    VELOCITY_FIELD_NUMBER: _builtins.int
    TURN_FIELD_NUMBER: _builtins.int
    REAR_LEFT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    REAR_LEFT_MODE_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_MODE_FIELD_NUMBER: _builtins.int
    sequence_id: _builtins.int
    """客户端侧命令序号，用于排查丢包、乱序或日志对齐。"""
    velocity: _builtins.float
    """C 端全局 Velocity 变量，单位为编码器脉冲/20ms。"""
    turn: _builtins.float
    """C 端全局 Turn 变量，单位为编码器脉冲/20ms 的差速修正量。"""
    rear_left_target_speed: _builtins.float
    """后左电机目标速度，单位为编码器脉冲/20ms。"""
    rear_right_target_speed: _builtins.float
    """后右电机目标速度，单位为编码器脉冲/20ms。"""
    rear_left_mode: Global___MotorMode.ValueType
    """后左电机控制模式。"""
    rear_right_mode: Global___MotorMode.ValueType
    """后右电机控制模式。"""
    def __init__(
        self,
        *,
        sequence_id: _builtins.int = ...,
        velocity: _builtins.float = ...,
        turn: _builtins.float = ...,
        rear_left_target_speed: _builtins.float = ...,
        rear_right_target_speed: _builtins.float = ...,
        rear_left_mode: Global___MotorMode.ValueType = ...,
        rear_right_mode: Global___MotorMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rear_left_mode", b"rear_left_mode", "rear_left_target_speed", b"rear_left_target_speed", "rear_right_mode", b"rear_right_mode", "rear_right_target_speed", b"rear_right_target_speed", "sequence_id", b"sequence_id", "turn", b"turn", "velocity", b"velocity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VehicleControlCommand: _TypeAlias = VehicleControlCommand  # noqa: Y015

@_typing.final
class StopEpisodeRequest(_message.Message):
    """客户端主动停止 episode 的请求。"""

    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    """停止原因；为空时服务端使用默认原因。"""
    def __init__(
        self,
        *,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopEpisodeRequest: _TypeAlias = StopEpisodeRequest  # noqa: Y015

@_typing.final
class ServerMessage(_message.Message):
    """服务端发回客户端的流式消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    STARTED_FIELD_NUMBER: _builtins.int
    OBSERVATION_FIELD_NUMBER: _builtins.int
    FINISHED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def started(self) -> Global___EpisodeStarted:
        """episode 已启动并返回任务元信息。"""

    @_builtins.property
    def observation(self) -> Global___ObservationFrame:
        """仿真观测帧。"""

    @_builtins.property
    def finished(self) -> Global___EpisodeFinished:
        """episode 已结束并返回汇总结果。"""

    @_builtins.property
    def error(self) -> Global___SimulationError:
        """episode 执行失败或请求不合法。"""

    def __init__(
        self,
        *,
        started: Global___EpisodeStarted | None = ...,
        observation: Global___ObservationFrame | None = ...,
        finished: Global___EpisodeFinished | None = ...,
        error: Global___SimulationError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "finished", b"finished", "observation", b"observation", "payload", b"payload", "started", b"started"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "finished", b"finished", "observation", b"observation", "payload", b"payload", "started", b"started"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["started", "observation", "finished", "error"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ServerMessage: _TypeAlias = ServerMessage  # noqa: Y015

@_typing.final
class EpisodeStarted(_message.Message):
    """episode 启动后的任务元信息。"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    TIME_LIMIT_S_FIELD_NUMBER: _builtins.int
    CONTROL_PERIOD_S_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """实际运行的任务编号。"""
    label: _builtins.str
    """任务展示名称。"""
    description: _builtins.str
    """任务说明。"""
    time_limit_s: _builtins.float
    """任务默认时间上限，单位秒。"""
    control_period_s: _builtins.float
    """本次 episode 实际采用的控制周期，单位秒。"""
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        label: _builtins.str = ...,
        description: _builtins.str = ...,
        time_limit_s: _builtins.float = ...,
        control_period_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_period_s", b"control_period_s", "description", b"description", "label", b"label", "task_id", b"task_id", "time_limit_s", b"time_limit_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EpisodeStarted: _TypeAlias = EpisodeStarted  # noqa: Y015

@_typing.final
class ObservationFrame(_message.Message):
    """单帧仿真观测数据。"""

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    SIM_TIME_S_FIELD_NUMBER: _builtins.int
    LINE_SENSOR_FIELD_NUMBER: _builtins.int
    IMU_FIELD_NUMBER: _builtins.int
    TASK_PROGRESS_FIELD_NUMBER: _builtins.int
    ENCODER_FIELD_NUMBER: _builtins.int
    MOTOR_DEBUG_FIELD_NUMBER: _builtins.int
    sequence_id: _builtins.int
    """服务端观测序号，随仿真步进递增。"""
    sim_time_s: _builtins.float
    """当前仿真时间，单位秒。"""
    @_builtins.property
    def line_sensor(self) -> Global___LineSensorFrame:
        """巡线传感器观测。"""

    @_builtins.property
    def imu(self) -> Global___ImuFrame:
        """IMU 航向观测。"""

    @_builtins.property
    def task_progress(self) -> Global___TaskProgressFrame:
        """当前任务完成进度。"""

    @_builtins.property
    def encoder(self) -> Global___EncoderFrame:
        """编码器与里程观测。"""

    @_builtins.property
    def motor_debug(self) -> Global___MotorDebugFrame:
        """电机速度环调试状态。"""

    def __init__(
        self,
        *,
        sequence_id: _builtins.int = ...,
        sim_time_s: _builtins.float = ...,
        line_sensor: Global___LineSensorFrame | None = ...,
        imu: Global___ImuFrame | None = ...,
        task_progress: Global___TaskProgressFrame | None = ...,
        encoder: Global___EncoderFrame | None = ...,
        motor_debug: Global___MotorDebugFrame | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encoder", b"encoder", "imu", b"imu", "line_sensor", b"line_sensor", "motor_debug", b"motor_debug", "task_progress", b"task_progress"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encoder", b"encoder", "imu", b"imu", "line_sensor", b"line_sensor", "motor_debug", b"motor_debug", "sequence_id", b"sequence_id", "sim_time_s", b"sim_time_s", "task_progress", b"task_progress"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ObservationFrame: _TypeAlias = ObservationFrame  # noqa: Y015

@_typing.final
class LineSensorFrame(_message.Message):
    """巡线传感器阵列的一帧观测。"""

    DESCRIPTOR: _descriptor.Descriptor

    DIGITAL_VALUES_FIELD_NUMBER: _builtins.int
    DARKNESS_FIELD_NUMBER: _builtins.int
    LINE_DETECTED_FIELD_NUMBER: _builtins.int
    WEIGHTS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    LATERAL_ERROR_M_FIELD_NUMBER: _builtins.int
    line_detected: _builtins.bool
    """当前是否检测到有效线路。"""
    error: _builtins.float
    """C 端 new_error，未检测到线路时保持上一帧误差。"""
    lateral_error_m: _builtins.float
    """线路相对车体中心的横向偏差，单位米；未检测到线路时不设置。"""
    @_builtins.property
    def digital_values(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """每个传感器的数字读数，通常 0 表示未检测到黑线、1 表示检测到黑线。"""

    @_builtins.property
    def darkness(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """每个传感器的黑度模拟值，顺序与 digital_values 一致。"""

    @_builtins.property
    def weights(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """C 端循迹权重，顺序与 digital_values 一致。"""

    def __init__(
        self,
        *,
        digital_values: _abc.Iterable[_builtins.int] | None = ...,
        darkness: _abc.Iterable[_builtins.float] | None = ...,
        line_detected: _builtins.bool = ...,
        weights: _abc.Iterable[_builtins.int] | None = ...,
        error: _builtins.float = ...,
        lateral_error_m: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_lateral_error_m", b"_lateral_error_m", "lateral_error_m", b"lateral_error_m"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_lateral_error_m", b"_lateral_error_m", "darkness", b"darkness", "digital_values", b"digital_values", "error", b"error", "lateral_error_m", b"lateral_error_m", "line_detected", b"line_detected", "weights", b"weights"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__lateral_error_m: _TypeAlias = _typing.Literal["lateral_error_m"]  # noqa: Y015
    _WhichOneofArgType__lateral_error_m: _TypeAlias = _typing.Literal["_lateral_error_m", b"_lateral_error_m"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__lateral_error_m) -> _WhichOneofReturnType__lateral_error_m | None: ...

Global___LineSensorFrame: _TypeAlias = LineSensorFrame  # noqa: Y015

@_typing.final
class ImuFrame(_message.Message):
    """IMU 航向观测。"""

    DESCRIPTOR: _descriptor.Descriptor

    YAW_DEG_FIELD_NUMBER: _builtins.int
    YAW_RATE_DEG_S_FIELD_NUMBER: _builtins.int
    yaw_deg: _builtins.float
    """车体偏航角，单位度，范围 [0, 360)。"""
    yaw_rate_deg_s: _builtins.float
    """车体偏航角速度，单位度/秒。"""
    def __init__(
        self,
        *,
        yaw_deg: _builtins.float = ...,
        yaw_rate_deg_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["yaw_deg", b"yaw_deg", "yaw_rate_deg_s", b"yaw_rate_deg_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ImuFrame: _TypeAlias = ImuFrame  # noqa: Y015

@_typing.final
class EncoderFrame(_message.Message):
    """编码器与里程观测，对齐 artemis-m0 的 20ms 控制 tick。"""

    DESCRIPTOR: _descriptor.Descriptor

    REAR_LEFT_PULSES_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_PULSES_FIELD_NUMBER: _builtins.int
    REAR_LEFT_TOTAL_PULSES_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_TOTAL_PULSES_FIELD_NUMBER: _builtins.int
    REAR_LEFT_MEASURE_SPEED_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_MEASURE_SPEED_FIELD_NUMBER: _builtins.int
    FORWARD_DISTANCE_CM_FIELD_NUMBER: _builtins.int
    rear_left_pulses: _builtins.float
    """后左电机本 tick 编码器脉冲。"""
    rear_right_pulses: _builtins.float
    """后右电机本 tick 编码器脉冲。"""
    rear_left_total_pulses: _builtins.float
    """后左电机累计脉冲。"""
    rear_right_total_pulses: _builtins.float
    """后右电机累计脉冲。"""
    rear_left_measure_speed: _builtins.float
    """后左电机测量速度，单位为脉冲/20ms。"""
    rear_right_measure_speed: _builtins.float
    """后右电机测量速度，单位为脉冲/20ms。"""
    forward_distance_cm: _builtins.float
    """按 CM_TO_PULSE 估算的前进距离，单位 cm。"""
    def __init__(
        self,
        *,
        rear_left_pulses: _builtins.float = ...,
        rear_right_pulses: _builtins.float = ...,
        rear_left_total_pulses: _builtins.float = ...,
        rear_right_total_pulses: _builtins.float = ...,
        rear_left_measure_speed: _builtins.float = ...,
        rear_right_measure_speed: _builtins.float = ...,
        forward_distance_cm: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["forward_distance_cm", b"forward_distance_cm", "rear_left_measure_speed", b"rear_left_measure_speed", "rear_left_pulses", b"rear_left_pulses", "rear_left_total_pulses", b"rear_left_total_pulses", "rear_right_measure_speed", b"rear_right_measure_speed", "rear_right_pulses", b"rear_right_pulses", "rear_right_total_pulses", b"rear_right_total_pulses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EncoderFrame: _TypeAlias = EncoderFrame  # noqa: Y015

@_typing.final
class MotorDebugFrame(_message.Message):
    """电机速度环调试状态。"""

    DESCRIPTOR: _descriptor.Descriptor

    REAR_LEFT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    REAR_LEFT_PID_OUTPUT_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_PID_OUTPUT_FIELD_NUMBER: _builtins.int
    REAR_LEFT_PWM_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_PWM_FIELD_NUMBER: _builtins.int
    REAR_LEFT_MODE_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_MODE_FIELD_NUMBER: _builtins.int
    rear_left_target_speed: _builtins.float
    rear_right_target_speed: _builtins.float
    rear_left_pid_output: _builtins.float
    rear_right_pid_output: _builtins.float
    rear_left_pwm: _builtins.float
    rear_right_pwm: _builtins.float
    rear_left_mode: Global___MotorMode.ValueType
    rear_right_mode: Global___MotorMode.ValueType
    def __init__(
        self,
        *,
        rear_left_target_speed: _builtins.float = ...,
        rear_right_target_speed: _builtins.float = ...,
        rear_left_pid_output: _builtins.float = ...,
        rear_right_pid_output: _builtins.float = ...,
        rear_left_pwm: _builtins.float = ...,
        rear_right_pwm: _builtins.float = ...,
        rear_left_mode: Global___MotorMode.ValueType = ...,
        rear_right_mode: Global___MotorMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rear_left_mode", b"rear_left_mode", "rear_left_pid_output", b"rear_left_pid_output", "rear_left_pwm", b"rear_left_pwm", "rear_left_target_speed", b"rear_left_target_speed", "rear_right_mode", b"rear_right_mode", "rear_right_pid_output", b"rear_right_pid_output", "rear_right_pwm", b"rear_right_pwm", "rear_right_target_speed", b"rear_right_target_speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MotorDebugFrame: _TypeAlias = MotorDebugFrame  # noqa: Y015

@_typing.final
class TaskProgressFrame(_message.Message):
    """任务路径与事件完成进度。"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    ACTIVE_SEGMENT_INDEX_FIELD_NUMBER: _builtins.int
    COMPLETED_EVENT_COUNT_FIELD_NUMBER: _builtins.int
    COMPLETED_EVENTS_FIELD_NUMBER: _builtins.int
    REACHED_GOAL_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """当前任务编号。"""
    active_segment_index: _builtins.int
    """当前所在路径段索引。"""
    completed_event_count: _builtins.int
    """已完成事件数量。"""
    reached_goal: _builtins.bool
    """是否已到达任务终点。"""
    @_builtins.property
    def completed_events(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """已完成事件名称列表。"""

    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        active_segment_index: _builtins.int = ...,
        completed_event_count: _builtins.int = ...,
        completed_events: _abc.Iterable[_builtins.str] | None = ...,
        reached_goal: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_segment_index", b"active_segment_index", "completed_event_count", b"completed_event_count", "completed_events", b"completed_events", "reached_goal", b"reached_goal", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskProgressFrame: _TypeAlias = TaskProgressFrame  # noqa: Y015

@_typing.final
class EpisodeFinished(_message.Message):
    """episode 结束消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    """结束原因，例如 goal_reached、time_limit、client_stopped 或 viewer_closed。"""
    @_builtins.property
    def summary(self) -> Global___SimulationSummary:
        """本次 episode 的汇总统计。"""

    def __init__(
        self,
        *,
        summary: Global___SimulationSummary | None = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason", "summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EpisodeFinished: _TypeAlias = EpisodeFinished  # noqa: Y015

@_typing.final
class SimulationError(_message.Message):
    """服务端错误消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    """错误说明。"""
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimulationError: _TypeAlias = SimulationError  # noqa: Y015

@_typing.final
class SimulationSummary(_message.Message):
    """episode 汇总统计。"""

    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    REACHED_GOAL_FIELD_NUMBER: _builtins.int
    ELAPSED_TIME_S_FIELD_NUMBER: _builtins.int
    ROUTE_LENGTH_M_FIELD_NUMBER: _builtins.int
    MAX_CROSS_TRACK_ERROR_M_FIELD_NUMBER: _builtins.int
    RMS_CROSS_TRACK_ERROR_M_FIELD_NUMBER: _builtins.int
    FINAL_POSE_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    """任务编号。"""
    reached_goal: _builtins.bool
    """是否到达任务终点。"""
    elapsed_time_s: _builtins.float
    """实际经过的仿真时间，单位秒。"""
    route_length_m: _builtins.float
    """任务路径总长度，单位米。"""
    max_cross_track_error_m: _builtins.float
    """最大横向路径误差，单位米。"""
    rms_cross_track_error_m: _builtins.float
    """横向路径误差均方根，单位米。"""
    @_builtins.property
    def final_pose(self) -> Global___Pose2D:
        """episode 结束时的车体位姿。"""

    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___SimulationEvent]:
        """episode 中记录到的任务事件。"""

    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        reached_goal: _builtins.bool = ...,
        elapsed_time_s: _builtins.float = ...,
        route_length_m: _builtins.float = ...,
        max_cross_track_error_m: _builtins.float = ...,
        rms_cross_track_error_m: _builtins.float = ...,
        final_pose: Global___Pose2D | None = ...,
        events: _abc.Iterable[Global___SimulationEvent] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["final_pose", b"final_pose"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["elapsed_time_s", b"elapsed_time_s", "events", b"events", "final_pose", b"final_pose", "max_cross_track_error_m", b"max_cross_track_error_m", "reached_goal", b"reached_goal", "rms_cross_track_error_m", b"rms_cross_track_error_m", "route_length_m", b"route_length_m", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimulationSummary: _TypeAlias = SimulationSummary  # noqa: Y015

@_typing.final
class SimulationEvent(_message.Message):
    """仿真过程中记录的任务事件。"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_S_FIELD_NUMBER: _builtins.int
    PATH_INDEX_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """事件名称。"""
    timestamp_s: _builtins.float
    """事件发生时的仿真时间，单位秒。"""
    path_index: _builtins.int
    """事件对应的路径采样点或路径段索引。"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        timestamp_s: _builtins.float = ...,
        path_index: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "path_index", b"path_index", "timestamp_s", b"timestamp_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimulationEvent: _TypeAlias = SimulationEvent  # noqa: Y015

@_typing.final
class Pose2D(_message.Message):
    """二维平面位姿。"""

    DESCRIPTOR: _descriptor.Descriptor

    X_M_FIELD_NUMBER: _builtins.int
    Y_M_FIELD_NUMBER: _builtins.int
    YAW_RAD_FIELD_NUMBER: _builtins.int
    x_m: _builtins.float
    """世界坐标系下的 x 坐标，单位米。"""
    y_m: _builtins.float
    """世界坐标系下的 y 坐标，单位米。"""
    yaw_rad: _builtins.float
    """世界坐标系下的偏航角，单位弧度。"""
    def __init__(
        self,
        *,
        x_m: _builtins.float = ...,
        y_m: _builtins.float = ...,
        yaw_rad: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x_m", b"x_m", "y_m", b"y_m", "yaw_rad", b"yaw_rad"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Pose2D: _TypeAlias = Pose2D  # noqa: Y015
